

CREATE TABLE 
Gender (
  Gender VARCHAR(6) NOT NULL
 ,CONSTRAINT PK_Gender_Gender PRIMARY KEY CLUSTERED (Gender)
) ON [PRIMARY]
CREATE TABLE Modules (
  ModuleCode NVARCHAR(10) NOT NULL
 ,ModuleName VARCHAR(50) NOT NULL
 ,Description VARCHAR(50) NOT NULL
 ,Resources VARBINARY(50) NOT NULL
 ,CONSTRAINT PK_Modules_ModuleCode PRIMARY KEY CLUSTERED (ModuleCode)
) ON [PRIMARY]
GO
CREATE TABLE Students (
  StudentNumber INT IDENTITY
 ,FirstName NVARCHAR(50) NOT NULL
 ,LastName VARCHAR(50) NOT NULL
 ,StudentImage IMAGE NOT NULL
 ,DOB DATE NOT NULL
 ,Gender VARCHAR(6) NOT NULL
 ,Phone VARCHAR(10) NOT NULL
 ,Address VARCHAR(50) NOT NULL
 ,ModuleCode NVARCHAR(10) NOT NULL
 ,CONSTRAINT PK_Students_StudentNumber PRIMARY KEY CLUSTERED (StudentNumber)
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE Students
ADD CONSTRAINT FK_Students_Gender_Gender FOREIGN KEY (Gender) REFERENCES dbo.Gender (Gender)
GO

ALTER TABLE Students
ADD CONSTRAINT FK_Students_Modules_ModuleCode FOREIGN KEY (ModuleCode) REFERENCES dbo.Modules (ModuleCode)
GO